version: '3.7'

x-common-php: &common-php
  image: gsmainclusivetechlab/interop-test-platform:develop
  restart: always
  environment:
    PROJECT_DOMAIN: ${PROJECT_DOMAIN}
  env_file: app.env
  depends_on:
    - mysqldb
    - redis
    - mailhog
  security_opt:
    - apparmor:unconfined
  cap_add:
    - SYS_PTRACE
  volumes:
    - certbot_certs:/etc/nginx/ssl/letsencrypt
    - certbot_www:/var/www/certbot
    - storage:/var/www/html/storage/app

services:
  app:
    <<: *common-php
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      CONTAINER_ROLE: app

  queue:
    <<: *common-php
    environment:
      CONTAINER_ROLE: queue

  mysqldb:
    image: mysql:8
    restart: always
    env_file: mysql.env
    healthcheck:
      retries: 10
      test: [CMD, mysqladmin, ping, -h, localhost]
      timeout: 20s
    volumes:
      - mysqldata:/var/lib/mysql:rw

  redis:
    image: redis:5
    restart: always
    environment:
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
    volumes:
      - redisdata:/data:rw

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - '8086:8025'

volumes:
  mysqldata: {}
  redisdata: {}
  ca_certs: {}
  certbot_certs: {}
  certbot_www: {}
  storage: {}
