@startuml
' declaring skinparam
skinparam rectangle {
	BackgroundColor None
	FontColor Black
}
skinparam usecaseMessageAlign center
skinparam ArrowColor Black


!define MMAPICOLOR Red
!define SWITCHAPICOLOR Orange
!define SPAPICOLOR Green
!define USSDAPICOLOR Blue

' declare title
'title Mobile Money API V1.0 and Mojaloop Hub \n System Flow
'header GSMA - Inclusive Tech Lab

scale 960 width

rectangle "===Payer" as payer
rectangle "===Service Provider" as sp
rectangle "===Mobile Money Operator 1" as mmo1
rectangle "===Mojaloop System" as switch
rectangle "===Mobile Money Operator 2" as mmo2

left to right direction

payer -[#SPAPICOLOR]-|> sp
payer <|-[#SPAPICOLOR]- sp
sp -[#MMAPICOLOR]-|> mmo1
sp <|-[#MMAPICOLOR]- mmo1
mmo1 -[#SWITCHAPICOLOR]-|> switch
mmo1 <|-[#SWITCHAPICOLOR]- switch
switch -[#SWITCHAPICOLOR]-|> mmo2
switch <|-[#SWITCHAPICOLOR]- mmo2

/'
legend bottom right
|= |= Type |
|<back:#MMAPICOLOR><color:#MMAPICOLOR>___</color></back>| Mobile Money API |
|<back:#SWITCHAPICOLOR><color:#SWITCHAPICOLOR>___</color></back>| Mojaloop API |
|<back:#SPAPICOLOR><color:#SPAPICOLOR>___</color></back>| User interacting over website or app|
endlegend
'/

@enduml
