@startuml p2p-authorized-transaction-nondisclosing-receive

'-----------------Transation Information-------------------'
' Sequence Diagram for a P2P transaction 
' Quoting Mode: Non-Disclosing
' Amount Type: Receive
' Amount: 100
' Payer FSP Fee: 1
' Payee FSP Fee: 0
' Payee FSP Comission: 1

'--------------------Skin Parameters----------------------'
skinparam SequenceMessageAlign center
skinparam ArrowFontSize 8
skinparam NoteFontSize 9
skinparam Style strictuml
skinparam ArrowColor Black
skinparam ParticipantPadding 20

!define MMAPICOLOR Red
!define SWITCHAPICOLOR Orange
!define SPAPICOLOR Green
!define USSDAPICOLOR Blue
!define FPXAPICOLOR Purple

skinparam sequence {
ParticipantFontSize 12
ActorFontSize 12
ParticipantBorderColor Black
ActorBorderColor Black
LifeLineBorderColor Black
LifeLineBackgroundColor Gray
EntityBorderColor Black
}

'----------------Constant String Values-------------------'
!$postq = "**POST/quotes**"
!$putq = "**PUT/quotes**"
!$postt = "**POST/transfers**"
!$putt = "**PUT/transfers**"
!$http202 = "**HTTP 202** (Accepted)"
!$http200 = "**HTTP 200** (OK)"
!$am = "amount"
!$amType = "amountType"
!$transAm ="transferAmount"
!$payeeRA = "payeeReceiveAmount"
!$payeefspcom = "payeefspCommission"

'----------------Participant Parameters-------------------'
actor Payer order 1
participant "Payer\nFSP" as payerfsp order 2
participant "Mojaloop" as Switch order 3 #FFAAAA
participant "Payee\nFSP" as payeefsp order 5
actor Payee order 6

'------------------Sequence Messages----------------------'
'---------------------------------------------------------'

Payer -> payerfsp: I would like Payee \n to receive 100 USD
activate payerfsp
payerfsp -> Switch: $postq\n$amType=RECEIVE,\n$am=100)
activate Switch #FFAAAA
payerfsp <-- Switch: $http202
Switch -> payeefsp: $postq\n($amType=RECEIVE,\n$am=100)
activate payeefsp
Switch <-- payeefsp: $http202
payeefsp -> payeefsp: Commission is 1 USD in\nPayee FSP for P2P
Switch <- payeefsp: $putq///<ID>//\n$transAm=99 USD,\n$payeeRA=100 USD,\n$payeefspcom=1 USD)
Switch --> payeefsp: $http200
deactivate payeefsp
payerfsp <-- Switch: $putq///<ID>//\n$transAm=99 USD,\n$payeeRA=100 USD,\n$payeefspcom=1 USD)
payerfsp --> Switch: $http200
deactivate Switch 
payerfsp -> payerfsp: Payer FSP keeps commission\nas fee, Payer should also pay\nfee of 1 USD
Payer <- payerfsp: Transferirg 100USD to Payee \n will cost you 101 USD \n including fees        
deactivate payerfsp


Payer -> payerfsp: Perform Transaction
activate payerfsp
payerfsp -> payerfsp: Reserve 99 USD from Payer FSP\naccount to Payee FSP account
payerfsp -> Switch: $postt\n($am=99 USD)
activate Switch #FFAAAA
payerfsp <-- Switch: $http202
Switch -> Switch: Reserve 99 USD from Payer FSP\naccount to Payee FSP account
Switch -> payeefsp: $postt\n($am=99 USD)
activate payeefsp
Switch <-- payeefsp:  $http202
payeefsp -> payeefsp: Transfer 99 USD from Switch\naccount and 1 USD from\ncomission account\nto Payee account
payeefsp -> Payee: You have received 100 USD\nfrom Payer
Switch <- payeefsp: $putt///<ID>//
Switch --> payeefsp: $http200
deactivate payeefsp
Switch -> Switch: Commit reserved transfer
payerfsp <- Switch: $putt///<ID>//
payerfsp --> Switch: $http200
deactivate Switch
Payer <- payerfsp: Transaction successful,\nyou have paid 1 USD in fee
deactivate payerfsp


@enduml