@startuml National Remittance


' declare title
'title Mobile Money API V1.0 and Mojaloop Hub \n System Flow
'header GSMA - Inclusive Tech Lab

'--------------------Skin Parameters----------------------'
skinparam SequenceMessageAlign center
skinparam ArrowFontSize 8
skinparam NoteFontSize 9
skinparam Style strictuml
skinparam ArrowColor Black
skinparam ParticipantPadding 20

!define MMAPICOLOR Red
!define SWITCHAPICOLOR Orange
!define SPAPICOLOR Green
!define USSDAPICOLOR Blue
!define FPXAPICOLOR Purple

skinparam sequence {
'ParticipantBackgroundColor DodgerBlue
ParticipantFontSize 12
ActorFontSize 12
ParticipantBorderColor Black
ActorBorderColor Black
LifeLineBorderColor Black
LifeLineBackgroundColor Gray
EntityBorderColor Black
}

'----------------Constant String Values-------------------'
!$postq = "**POST/quotes**"
!$putq = "**PUT/quotes**"
!$postt = "**POST/transfers**"
!$putt = "**PUT/transfers**"
!$http202 = "**HTTP 202** (Accepted)"
!$http200 = "**HTTP 200** (OK)"
!$am = "amount"
!$amType = "amountType"
!$transAm ="transferAmount"
!$payeeRA = "payeeReceiveAmount"
!$payeeFSPcom = "payeeFSPCommission"

'----------------Participant Parameters-------------------'
actor Payer order 1
participant "Payer\nFSP" as PayerFSP order 2
participant "Mojaloop" as Switch order 3 #FFAAAA
participant "FXP" as fxp order 4 #9DC183
participant "Payee\nFSP" as PayeeFSP order 5
actor Payee order 6
'Switch *---- fxp

'------------------Sequence Messages----------------------'
'---------------------------------------------------------'
Payer [#SPAPICOLOR]-> PayerFSP: I would like Payee \n to receive 1840 ZAR
activate PayerFSP
PayerFSP [#MMAPICOLOR]-> Switch: $postq\n$amType=RECEIVE,\n$am=1840 ZAR)
note right of Switch #FFAAAA
This Participant is the
module for international
transaction
end note
activate Switch #FFAAAA
Switch [#FPXAPICOLOR]-> fxp: $postq\n(Type=CONVERSION,\n$am=1840 ZAR ) 
activate fxp #9DC183
Switch <-[#FPXAPICOLOR]- fxp: $http202
Switch <-[#FPXAPICOLOR] fxp: $putq///<ID>//\n$transAm=1840 ZAR,\n$payeeRA=100 USD,\n$payeeFSPcom=1 USD)
Switch -[#FPXAPICOLOR]-> fxp: $http200
deactivate fxp

PayerFSP <--[#MMAPICOLOR] Switch: $http202
Switch [#MMAPICOLOR]-> PayeeFSP: $postq\n($amType=RECEIVE,\n$am=100 USD )
activate PayeeFSP
Switch <-[#MMAPICOLOR]- PayeeFSP: $http202
PayeeFSP [#MMAPICOLOR]-> PayeeFSP: Commission is 1 USD in\nPayee FSP for\n International Remittance
Switch <-[#MMAPICOLOR] PayeeFSP: $putq///<ID>//\n$transAm=1840 ZAR,\n$payeeRA=100 USD,\n$payeeFSPcom=1 USD)
Switch -[#MMAPICOLOR]-> PayeeFSP: $http200
deactivate PayeeFSP
PayerFSP <-[#MMAPICOLOR]- Switch: $putq///<ID>//\n$transAm=1840 ZAR,\n$payeeRA=100 USD,\n$payeeFSPcom=1 USD)
PayerFSP -[#MMAPICOLOR]-> Switch: $http200
deactivate Switch 
PayerFSP [#MMAPICOLOR]-> PayerFSP: Payer FSP keeps commission\nas fee, Payer should also pay\nfee of 20 ZAR
Payer <-[#SPAPICOLOR] PayerFSP: Transferirg 1840 ZAR to Payee \n will cost you 1860 ZAR \n including fees
deactivate PayerFSP


Payer [#SPAPICOLOR]-> PayerFSP: Perform Transaction
activate PayerFSP
PayerFSP [#SPAPICOLOR]-> PayerFSP: Reserve 99 USD from Payer FSP\naccount to Payee FSP account
PayerFSP [#MMAPICOLOR]-> Switch: $postt\n($am=99 USD)
activate Switch #FFAAAA
PayerFSP <-[#MMAPICOLOR]- Switch: $http202
Switch [#MMAPICOLOR]-> Switch:
Switch [#MMAPICOLOR]-> PayeeFSP: $postt\n($am=99 USD)
activate PayeeFSP
Switch <-[#MMAPICOLOR]- PayeeFSP:  $http202
PayeeFSP [#SPAPICOLOR]-> PayeeFSP: Transfer 99 USD from Switch\naccount and 1 USD from\ncomission account\nto Payee account
PayeeFSP [#SPAPICOLOR]-> Payee: You have received 100 USD\nfrom Payer
Switch <-[#MMAPICOLOR] PayeeFSP: $putt///<ID>//
Switch -[#MMAPICOLOR]-> PayeeFSP: $http200
deactivate PayeeFSP
Switch [#MMAPICOLOR]-> Switch: Commit reserved transfer
PayerFSP <-[#MMAPICOLOR] Switch: $putt///<ID>//
PayerFSP -[#MMAPICOLOR]-> Switch: $http200
deactivate Switch
Payer <-[#SPAPICOLOR] PayerFSP: Transaction successful,\nyou have paid 1 USD in fee
deactivate PayerFSP


@enduml