version: '3.7'

x-ops-service: &ops-service
  image: gsmainclusivetechlab/interop-test-platform:${CIRCLE_SHA1:-latest}
  depends_on:
    - mysqldb
  env_file: service.env
  environment:
    WAIT_HOSTS: mysqldb:3306
    WAIT_SLEEP_INTERVAL: 5
    WAIT_HOSTS_TIMEOUT: 100
  networks:
    internal:

services:
  seed:
    <<: *ops-service
    command: sh -c "/wait && php artisan migrate:refresh --seed"

  migrate:
    <<: *ops-service
    command: sh -c "/wait && php artisan migrate"

  test:
    <<: *ops-service
    # Mount the src directory as `src` so coverage is mapped correctly
    command:
      sh -c "/wait && mkdir -p ../results && phpdbg -qrr vendor/bin/phpunit
      --coverage-html ../results/coverage-report-html --coverage-clover
      ../results/coverage-report-clover/clover.xml"

  has-db:
    <<: *ops-service
    image: gsmainclusivetechlab/interop-test-platform/mysqldb:${CIRCLE_SHA1:-latest}
    env_file: service.env
    command:
      sh -c "/wait && mysql -h mysqldb -u $$DB_USERNAME -p$$DB_PASSWORD -e
      \"SELECT * FROM migrations\" -N -B $$DB_DATABASE >/dev/null && echo
      \"Database already setup.\"" || (echo "No database found" && false)

  backup:
    <<: *ops-service
    image: gsmainclusivetechlab/interop-test-platform/mysqldb:${CIRCLE_SHA1:-latest}
    env_file: service.env
    command:
      sh -c "(/wait > /dev/null) && mysqldump -h mysqldb -u $$DB_USERNAME
      -p$$DB_PASSWORD $$DB_DATABASE 2>/dev/null"

  selenium:
    image: selenium/standalone-chrome:85.0
    links:
      - app:sdnet.test
    # this allows selenium to use the host's shared memory
    volumes:
      - /dev/shm:/dev/shm
    networks:
      internal:

  dusk:
    <<: *ops-service
    depends_on:
      - mysqldb
      - selenium
      - mailhog
    command: sh -c "/wait && php artisan dusk"
