version: '3.7'

services:
    phpmyadmin:
        depends_on:
            - mysqldb
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_HOST=mysqldb
        ports:
            - 8080:80
        volumes:
            - /sessions
