version: '3.7'

services:
  app:
    restart: always
  # scheduler:
  # restart: always
  queue:
    restart: always
  redis:
    restart: always
  mysqldb:
    restart: always

# TODO?: mount to well-defined directory on host
volumes:
  mysqldata:
  redisdata:
  certbot_certs:
  certbot_www: