#  Adds volumes allowing local modifications to files inside the running container
version: '3.7'

services:
  webpack:
    user: $HOST_UID
    build:
      context: src
      dockerfile: webpack.Dockerfile
    volumes:
      - ./src/resources:/usr/src/app/resources
      - ./src/public/assets:/usr/src/app/public/assets
      - ${PWD}/src/npm-package:/usr/src/app/npm-package
