#  Adds volumes allowing local modifications to files inside the running container
version: '3.7'

services:
  webpack:
    user: $HOST_UID
    build:
      context: src
      dockerfile: webpack.Dockerfile
    volumes:
      - ./src:/usr/src/app
