name: CI/CD
on:
  push:
    branches:
      - feature/github-actions
jobs:
  build:
    name: Build image and push to docker hub
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Copy configuration files
        env:
          HOST_WEB_PORT: 80
          HOST_HTTPS_WEB_PORT: 443
          PROJECT_DOMAIN: www.example.com
          HOST_MAILHOG_PORT: 8080
          HOST_PHPMYADMIN_PORT: 8081
          DB_DATABASE: itp-test
          DB_USERNAME: itp-test-user
          DB_PASSWORD: itp-test-pw
        run: envsubst < service.example.env > service.env

      - name: Building docker images
        run: |
          yarn prepare:docker
          docker-compose -f docker-compose.ci.yml build app

      - name: Run tests and get coverage
        run: |
          docker-compose -f docker-compose.ci.yml run app sh -c "/wait && cd /var/www && mv html src && cd src && phpdbg -qrr vendor/bin/phpunit -d memory_limit=512M --coverage-clover=results/clover.xml --log-junit results/results.xml"
          docker cp $(docker ps -alq):/var/www/src/results .
          docker-compose -f docker-compose.ci.yml down -v

      - name: Codecov Coverage Reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./results/clover.xml
          fail_ci_if_error: true # optional (default = false)
          #verbose: true # optional (default = false)
